  FROM python:3.11-slim

  ENV PYTHONDONTWRITEBYTECODE=1 \
      PYTHONUNBUFFERED=1

  WORKDIR /app

  RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
      curl \
      && rm -rf /var/lib/apt/lists/*

  RUN pip install --no-cache-dir --upgrade pip && \
      pip install --no-cache-dir \
      fastapi \
      "uvicorn[standard]" \
      sqlalchemy \
      asyncpg \
      python-dotenv \
      python-jose \
      python-multipart \
      pydantic \
      bcrypt \
      passlib \
      email-validator

  COPY app ./app

  EXPOSE 8000

  CMD ["uvicorn", "app.interfaces.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
